### ISSUE TITLE
Prototype an ML Pipeline up to a fully customized preprocessor

### ISSUE THREAD

**Issue by Afraz496** [Afraz496/data-science-portfolio#2]
Create a `train_test.py` file that acts as a hub and uses `parse_args()` to change arguments for our Input to the pipeline.

Then create a function called `fit_processor()` - please use the notebook `housing-price.ipynb` for guidance.

And get to a point in the script with `norm_X_train` and `norm_X_test`

**Comment by vnirwan** [comment]
Added preprocess function files under Function folder
